language: generic

sudo: false

notifications:
    email: false

addons:
    apt:
        packages:
            - xvfb  # For mayavi headless (needed to build the gallery)

# Need to fetch a deeper clone because the default depth Travis uses (50) isn't
# enough to get the git tags so versioneer can't find the correct version
# number.
git:
    depth: 100

env:
    global: # For pushing the built docs to the fatiando/dev repo
        - secure: cXRXecOJ0LpQBPfl/CvrrvuDTQpN0zZ1mpGG4rs02yWRmRoykqzJpPNHBHZ1MWEHGwOP9QqXjuPTRPEHYBP4I9V/7uHgrd4rIg50gonyr0LdQFLL9QxsM6SMH/zHyma+hpWmg2k3ad6zBd0GFkaACtVlS/x2F8JG+W6TrU/oL+I=

matrix:
    include:
        - os: linux
          env: PYTHON=2.7 BUILD_DOCS=true COVERAGE=false
        - os: linux
          env: PYTHON=2.7 BUILD_DOCS=false COVERAGE=true
        - os: osx
          env: PYTHON=2.7 BUILD_DOCS=false COVERAGE=false

before_install:
    # Get Miniconda from Continuum
    # Need to source the script to set the PATH variable in this environment
    # (not the scripts environment)
    - source ci/install-miniconda.sh
    - cp ci/matplotlibrc .
    # Create a conda env to install required libraries
    - conda update --yes conda
    - conda create -n testenv --yes pip python=$PYTHON
    - source activate testenv

install:
    - if [ "$BUILD_DOCS" == "true" ]; then conda install --yes mayavi && pip install -r ci/requirements-pip.txt; fi
    - conda install --yes --file ci/requirements-conda.txt
    - pip install coveralls==0.5
    # Show installed pkg information for postmortem diagnostic
    - conda list
    # Package Fatiando and install
    - python setup.py sdist --formats=gztar
    - pip install dist/fatiando-*.tar.gz

script:
    - bash ci/run-tests.sh
    - make pep8
    - bash ci/build-docs.sh

after_success:
    - bash ci/submit-coverage.sh
    - bash ci/update-website.sh
