name: fatiando
channels:
    - conda-forge
    - defaults
dependencies:
    - python=2.7
    - pip
    - numpy
    - scipy
    - matplotlib
    - numba
    - future
    - basemap
    - pillow
    - jupyter
    - sphinx
    - pytest
    - pytest-cov
    - coverage
    - flake8
    - pylint
    - cython
    - sphinx-gallery
    - sphinx_bootstrap_theme
